language: sh
before_install:
- sudo apt-get update
- sudo apt-get install jq
install: "./install_sloppy_cli.sh"
script: "./wikifundi_management.sh cron"
env:
  global:
  - secure: "gupZcxL3XHQn/XGozs3BMSdgoC24SRJP9pl7WLxfEQAH0B6nCpNmIOttcgSNsqRc6LPDE4TBiZn76r9hhPjKlCVKXThAH9fxwdT26GxxlHEBjbiYJVbe/uMLp4/Nrd2qnVoVschYv6v/+FGfgSqHw7Vcs+v62mkxb6c0a2cjInXn8CGj/RZ2hosNc1yebH5jByPSuRBo84l3fR2bo5mxGCTtqm4Qd/ChMsc2nQqEt4SCBilWBqL2ne604wOoPXbqqvcwPwQVpudqi2bSblCamWa0j2Nw7BzkpeJHTcVMoU5RYw7iq3Ja0IBbh5fu7/QjS0Iv5hMRkfnsdIMuQdDnuizz+gUJIPA2bzKk/MNB8AIPPfCMMV2oD/SLPAZifhZAY/NyxzhunEKjcgg20Zom0k2bcRxr0Mv67F0p0ldyQ8hPjGdpEZIp5s/RhnHoH6BXFDi61oO1DI+wr1xFNq9kgaFGFQMGvO7th/pPbDUFuxNi97aIuGZGeT7OrgyGaZ+hDhzMkiWGPoILvMvWthJdnp2DFMX0c4kIcT81bHVLLl5zAbCoWrR2QAWrOASbUeSCi52gX/ieGuJuLYqHGy+T/5UGdDgv5NmhtnGcxMgDD/+0/pfk3/OSdKTCP+ZeypRFFpNR+3rUSzTCyQNQLuVlxC2Wdl3r7CWNeSwtM3jSFyk="
