language: sh
before_install:
- sudo apt-get update
- sudo apt-get install jq
install: "./install_sloppy_cli.sh"
script: "./wikifundi_management.sh cron"
env:
  global:
  - secure: "e9rrtXlwZB0q1qEVJqxmB9l6k0wy3Uu/GWVoAiz4AccciLYObwFK91tuKrNcLzcrdduVlglZZ6NWniHbZZDwmbDTm1QaQTPyvP1ca3hvfLqKHi4Dv+p+UlR0bd9axnjI6yKenHDxmJscN8YzMB2IRvwahIYg3UrDHGN/aUql4SKWrOOuTWx1nKUM59SB0VHv+PR1cSK2mxk6+3AU5MWFlmidyy9MJduIxOyotVVDdqFknXRxBriL9u9Pn4VRBqNJIc2fK7HTc6x+/Xo6ESg9EU90CsgC/2XYMIzrF3oDL0mr1AGZoUCAvOKBKxdh2quUiKEsekTCkRtZL6dNpJtdT5oFt8PQYtllkZnhaDajQWG0IAcHjo/xAteiwx35essGU8AfGjnsrSVM66XtvJ2S9h0U15IcgMoLokm6m5F0SSRnDJSfR2YoBq/nJ/P24HyWp416n7XYyCJuRw0erPCHaVShAV7N4OeWxsNggjCaM5E6AhRHK8YjPx3g6GgPcdF3ZB63eSst7GPKoeo6uXZ6G1BjkwGLgAhf0+hKae/KhNh02we6LS8tzfy+oTuUqAARTflLQeiG20+tGHkTuoOHHA3qKxL5bk3pMQIgh7avL1JH3+wpPT4ALVO8zJ3v1pMQrjqnYtb/DAgrKKHFYO/Ld5cx3eA1fTM9D3BzFh2AIcA="
