language: sh
before_install:
- sudo apt-get update
- sudo apt-get install jq
install: "./install_sloppy_cli.sh"
script: "./wikifundi_management.sh cron"
env:
  global:
  - secure: "vBL665DDGTScoqgofrL3x4KhfBC8LycSrYhKtAKx8pWYEYvB+/YeFKBtGoTh5Di1g6/rhp9KS89jSY8Ku0oU8j4dQTQPJeufi4rtOBBsoyXS3iSn+9D5fXucqeoNAqX7T4xkMaf7FdezFfrf9RWRAj9gKyPCqDOIdCQ5bOS4yMWrURhJhz06EMCjDIM7SjJ0sDrW09KEFIN+aswg0OVrBIKx3quvNQsdMOQo0i+7qczF7A7p9bPKWIuY7VEBE6Am3qDliPbwe9Ig3QxATp3ZPoNdBW0ZMHRvXH1Dsqkjs9fXL04gIe3Uuwj8L1aXXb2TE/CfLxCNr83b2ZFSC7FAasqYoP5vE4a2k2HIxH3okLVSQTamJHXKCK2IG/9KGbC1WXlkaBNxcbtAr1yKgdpg5tQhgmkv3xVZwSoD4BXutvVUf/iRqarZ+MOU0ZjfQ2Ka5quSnH47LHSM//6IlzdqgV8uNKIFoiOsdYXtElhMH3ZNCw46cessbiPHfiC3CKzxd0PQWKcsxv8AEFuPJCgxOBWoXPk3fpE2vCYNWW//smA2bctPpuyz5PDZpxYasmHEo7RiGBu0//JSQkI87dyFtlKo1tYvN1oJWi/uemhiIKvIMSCOHcNindvTPK7lLIuTG5ds+ZgN3vbSM2r+9PD39/RRNNbsbphbvjxlwaqbxBg="
